[2024-04-02 21:29:26,578] ERROR log_exception() L828  Exception on /bop/ [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/home/slsn/repos/bop_land_api/blueprints/bop.py", line 106, in get_bop
    return apresenta_bops(bop), 200
  File "/home/slsn/repos/bop_land_api/schemas/bop.py", line 28, in apresenta_bops
    for bop in bops:
TypeError: 'BOP' object is not iterable
[2024-04-02 21:29:26,579] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:26] "[35m[1mGET /bop/?sonda=NSXX HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:44,167] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:44] "[32mGET /bop?sonda=aaa HTTP/1.1[0m" 308 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:44,172] WARNING get_bop() L101  Erro ao buscar BOP 'aaa', BOP n√£o encontrado na base :/ - call_trace=/home/slsn/repos/bop_land_api/blueprints/bop.py L101 
[2024-04-02 21:29:44,172] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:44] "[33mGET /bop/?sonda=aaa HTTP/1.1[0m" 404 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:44,252] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:44] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:45,141] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:45] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:48,598] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:48] "[32mGET /bop?sonda=aa HTTP/1.1[0m" 308 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:29:48,603] WARNING get_bop() L101  Erro ao buscar BOP 'aa', BOP n√£o encontrado na base :/ - call_trace=/home/slsn/repos/bop_land_api/blueprints/bop.py L101 
[2024-04-02 21:29:48,603] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:29:48] "[33mGET /bop/?sonda=aa HTTP/1.1[0m" 404 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:31:22,938] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:31:22] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:31:29,135] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:31:29] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:14,276] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:14] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:24,015] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:24] "[32mGET /bop?sonda=a HTTP/1.1[0m" 308 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:24,022] ERROR log_exception() L828  Exception on /bop/ [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/home/slsn/repos/bop_land_api/blueprints/bop.py", line 106, in get_bop
    return apresenta_bops(bop), 200
  File "/home/slsn/repos/bop_land_api/schemas/bop.py", line 28, in apresenta_bops
    for bop in bops:
TypeError: 'BOP' object is not iterable
[2024-04-02 21:32:24,023] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:24] "[35m[1mGET /bop/?sonda=a HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:30,136] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:30] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:31,177] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:31] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:36,366] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:36] "[32mGET /bop?sonda=aaaa HTTP/1.1[0m" 308 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:36,371] WARNING get_bop() L101  Erro ao buscar BOP 'aaaa', BOP n√£o encontrado na base :/ - call_trace=/home/slsn/repos/bop_land_api/blueprints/bop.py L101 
[2024-04-02 21:32:36,371] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:36] "[33mGET /bop/?sonda=aaaa HTTP/1.1[0m" 404 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:40,214] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:40] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:32:41,630] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:32:41] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:20,620] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:20] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:35,538] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:35] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:36,566] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:36] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:37,327] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:37] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:41,769] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:41] "GET /valvulas HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:41,778] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:41] "GET /preventores HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:44,718] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:44] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:36:57,497] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:36:57] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:37:01,260] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:37:01] "OPTIONS /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:37:01,263] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:37:01] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-02 21:37:02,533] INFO _log() L96   127.0.0.1 - - [02/Apr/2024 21:37:02] "GET /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
