[2024-03-31 00:01:54,579] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:01:54,580] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:02:03,456] ERROR log_exception() L828  Exception on /secao [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'get_dado_secao' did not return a valid response. The function either returned None or ended without a return statement.
[2024-03-31 00:02:03,456] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:02:03] "[35m[1mGET /secao HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:02:10,879] ERROR log_exception() L828  Exception on /secao [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'get_dado_secao' did not return a valid response. The function either returned None or ended without a return statement.
[2024-03-31 00:02:10,880] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:02:10] "[35m[1mGET /secao HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:02:38,760] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:02:38] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:02:46,301] ERROR log_exception() L828  Exception on /secao [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 873, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 892, in finalize_request
    response = self.make_response(rv)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1164, in make_response
    raise TypeError(
TypeError: The view function for 'get_dado_secao' did not return a valid response. The function either returned None or ended without a return statement.
[2024-03-31 00:02:46,302] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:02:46] "[35m[1mGET /secao HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:04:12,541] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:04:12,541] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:04:40,097] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:04:40] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:04:43,468] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:04:43] "GET /secao HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:07:47,966] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:07:47,967] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:08:06,288] ERROR log_exception() L828  Exception on /login [POST] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/home/slsn/repos/bop_land_api/app.py", line 86, in login
    print("se√ß√£o feliz: "+ session)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/local.py", line 368, in r_op
    return op(other, obj)
TypeError: can only concatenate str (not "SecureCookieSession") to str
[2024-03-31 00:08:06,292] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:08:06] "[35m[1mPOST /login HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:08:45,599] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:08:45,599] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:08:54,554] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:08:54] "POST /login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:09:00,285] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:09:00] "[31m[1mGET /secao HTTP/1.1[0m" 400 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:09:41,608] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:09:41] "GET /secao HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:09:54,423] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:09:54] "GET /secao HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:09:55,819] INFO _log() L96   127.0.0.1 - - [31/Mar/2024 00:09:55] "GET /secao HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-03-31 00:14:25,343] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.24.235.173:5000 - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
