[2024-04-09 11:05:59,014] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:06,138] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:06] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:23,089] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:23] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:23,595] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:23] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:30,942] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:30] "OPTIONS /bop/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:30,955] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:30] "[31m[1mGET /bop/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:06:34,498] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:06:34] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:11:25,836] INFO _log() L96    * Detected change in '/home/slsn/repos/bop_land_api/blueprints/auth.py', reloading - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:11:25,946] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:11:39,311] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:11:39] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:12:00,186] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:12:00] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:12:00,708] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:12:00] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:13:29,883] INFO _log() L96    * Detected change in '/home/slsn/repos/bop_land_api/blueprints/auth.py', reloading - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:13:29,991] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:13:32,007] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:13:32] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:13:48,775] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:13:48] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:13:49,282] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:13:49] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:15:35,597] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:15:35] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:16:37,833] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:16:37] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:16:38,347] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:16:38] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:19:12,598] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:19:12] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:19:24,954] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:19:24] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:19:25,471] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:19:25] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:20:19,044] INFO _log() L96    * Detected change in '/home/slsn/repos/bop_land_api/blueprints/auth.py', reloading - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:20:19,158] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:20:33,138] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:20:33] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:20:49,603] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:20:49] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:20:50,118] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:20:50] "[31m[1mGET /auth/ HTTP/1.1[0m" 401 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:26:38,902] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:26:38] "POST /auth/login HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:26:59,607] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:26:59] "GET /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:27:24,430] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:27:24] "GET /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:08,385] INFO _log() L96    * Detected change in '/home/slsn/repos/bop_land_api/blueprints/auth.py', reloading - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:08,499] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:16,875] ERROR log_exception() L828  Exception on /auth/ [GET] - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py L828 
Traceback (most recent call last):
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/home/slsn/repos/bop_land_api/blueprints/auth.py", line 96, in get_dado_secao
    current_user = request.current_user
AttributeError: 'Request' object has no attribute 'current_user'
[2024-04-09 11:28:16,876] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:28:16] "[35m[1mGET /auth/ HTTP/1.1[0m" 500 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:33,038] INFO _log() L96    * Detected change in '/home/slsn/repos/bop_land_api/blueprints/auth.py', reloading - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:33,130] INFO _log() L96    * Restarting with stat - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:28:39,170] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:28:39] "GET /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:29:29,356] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:29:29] "GET /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
[2024-04-09 11:33:23,602] INFO _log() L96   127.0.0.1 - - [09/Apr/2024 11:33:23] "OPTIONS /auth/ HTTP/1.1" 200 - - call_trace=/home/slsn/repos/bop_land_api/.venv/lib/python3.10/site-packages/werkzeug/_internal.py L96  
